import { test, expect, type BrowserContext } from "@playwright/test";

const origin = process.env.E2E_APP_ORIGIN ?? "http://localhost:3100";
const password = "A memorable test password 72!";
const username = () => `flow${Math.random().toString(36).slice(2, 10)}`;
const post = (context: BrowserContext, path: string, data: unknown) => context.request.post(path, { headers: { origin }, data });

test("login resumes a table and settings lead back to the same seat", async ({ page, context, browser }) => {
  const user = username();
  expect((await post(context, "/api/account", { username: user, displayName: "Jordan Lee", password })).status()).toBe(201);
  await post(context, "/api/account/logout", {});
  const host = await browser.newContext({ baseURL: origin });
  const seat = await (await post(host, "/api/games", { name: "Table Host" })).json();
  await page.goto(`/g/${seat.code}`);
  await page.getByRole("link", { name: "Log in before joining" }).click();
  await expect(page).toHaveURL(new RegExp(`/login\\?next=%2Fg%2F${seat.code}$`));
  await expect(page.getByRole("link", { name: "Back to the table" })).toHaveAttribute("href", `/g/${seat.code}`);
  const login = page.getByRole("form", { name: "Log in", exact: true });
  await login.getByLabel("Username", { exact: true }).fill(user);
  await login.getByLabel("Password", { exact: true }).fill(password);
  await login.getByRole("button", { name: "Log in", exact: true }).click();
  await expect(page).toHaveURL(`${origin}/g/${seat.code}`);
  const join = page.getByRole("form", { name: "Join table" });
  await expect(join).toContainText("Playing as Jordan Lee");
  await expect(join.getByRole("textbox")).toHaveCount(0);
  await join.getByRole("button", { name: "Take a seat" }).click();
  await page.getByRole("button", { name: "Skip", exact: true }).click();
  const before = await (await context.request.get(`/api/games/${seat.code}/state`)).json();
  expect(before.me).toBeTruthy();
  await page.getByRole("link", { name: "Account settings" }).click();
  await expect(page.getByRole("region", { name: "Friends", exact: true })).toHaveCount(0);
  await expect(page.getByRole("heading", { name: "Jordan Lee", exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "Change display name" }).click();
  const edit = page.getByRole("form", { name: "Display name settings" });
  await edit.getByLabel("Display name", { exact: true }).fill("Jordan Lane");
  await edit.getByRole("button", { name: "Save display name" }).click();
  await expect(page.getByRole("status")).toContainText("Display name updated");
  await page.getByRole("link", { name: "Back to the table" }).click();
  await expect(page).toHaveURL(`${origin}/g/${seat.code}`);
  await expect(page.getByRole("dialog", { name: "How Cambio works" })).toHaveCount(0);
  await expect(page.getByText("Jordan Lane", { exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByText("Jordan Lane", { exact: true })).toBeVisible();
  const after = await (await context.request.get(`/api/games/${seat.code}/state`)).json();
  expect(after.me).toBe(before.me);
  expect(after.view.public.players.filter((p: { profileId: string | null }) => p.profileId)).toHaveLength(1);
  await host.close();
});

test("signup from a player profile returns to that player before adding them", async ({ page, browser }) => {
  const owner = await browser.newContext({ baseURL: origin });
  const ownerName = username();
  expect((await post(owner, "/api/account", { username: ownerName, displayName: "Riley Chen", password })).status()).toBe(201);
  await page.goto(`/p/${ownerName}`);
  await page.getByRole("link", { name: "Log in to add friends" }).click();
  await page.getByRole("button", { name: "Create account", exact: true }).click();
  const form = page.getByRole("form", { name: "Create account", exact: true });
  await form.getByLabel("Username", { exact: true }).fill(username());
  await form.getByLabel("Display name", { exact: true }).fill("Sam Rivera");
  await form.getByLabel("Password", { exact: true }).fill(password);
  await form.getByLabel("Confirm password", { exact: true }).fill(password);
  await form.getByRole("button", { name: "Create account", exact: true }).click();
  await expect(page).toHaveURL(`${origin}/p/${ownerName}`);
  await expect(page.getByRole("heading", { name: "Riley Chen", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Add friend", exact: true }).click();
  await expect(page.getByRole("button", { name: "Request sent" })).toBeDisabled();
  await page.reload();
  await expect(page.getByRole("button", { name: "Request sent" })).toBeDisabled();
  await page.getByRole("link", { name: "Account settings" }).click();
  await expect(page.getByRole("link", { name: "Back to the profile" })).toHaveAttribute("href", `/p/${ownerName}`);
  await page.goto("/login?next=//example.com");
  await expect(page).toHaveURL(`${origin}/`);
  await owner.close();
});
