import { test, expect, type BrowserContext } from "@playwright/test";

const origin = process.env.E2E_APP_ORIGIN ?? "http://localhost:3100";
const password = "A memorable test password 72!";
const username = () => `flow${Math.random().toString(36).slice(2, 10)}`;
const post = (context: BrowserContext, path: string, data: unknown) => context.request.post(path, { headers: { origin }, data });

test("login resumes a table and settings lead back to the same seat", async ({ page, context, browser }) => {
  const user = username();
  expect((await post(context, "/api/account", { username: user, displayName: "Jordan Lee", password })).status()).toBe(201);
  await post(context, "/api/account/logout", {});
  const host = await browser.newContext({ baseURL: origin });
  const seat = await (await post(host, "/api/games", { name: "Table Host" })).json();
  await page.goto(`/g/${seat.code}`);
  await page.getByRole("link", { name: "Log in before joining" }).click();
  await expect(page).toHaveURL(new RegExp(`/login\\?next=%2Fg%2F${seat.code}$`));
  await expect(page.getByRole("link", { name: "Back to the table" })).toHaveAttribute("href", `/g/${seat.code}`);
  const login = page.getByRole("form", { name: "Log in", exact: true });
  await login.getByLabel("Username", { exact: true }).fill(user);
  await login.getByLabel("Password", { exact: true }).fill(password);
  await login.getByRole("button", { name: "Log in", exact: true }).click();
  await expect(page).toHaveURL(`${origin}/g/${seat.code}`);
  const join = page.getByRole("form", { name: "Join table" });
  await expect(join).toContainText("Playing as Jordan Lee");
  await expect(join.getByRole("textbox")).toHaveCount(0);
  await join.getByRole("button", { name: "Take a seat" }).click();
  await page.getByRole("button", { name: "Skip", exact: true }).click();
  const before = await (await context.request.get(`/api/games/${seat.code}/state`)).json();
  expect(before.me).toBeTruthy();
  await page.getByRole("link", { name: "Account settings" }).click();
  await expect(page.getByRole("region", { name: "Friends", exact: true })).toHaveCount(0);
  await expect(page.getByRole("heading", { name: "Jordan Lee", exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "Change display name" }).click();
  const edit = page.getByRole("form", { name: "Display name settings" });
  await edit.getByLabel("Display name", { exact: true }).fill("Jordan Lane");
  await edit.getByRole("button", { name: "Save display name" }).click();
  await expect(page.getByRole("status")).toContainText("Display name updated");
  await page.getByRole("link", { name: "Back to the table" }).click();
  await expect(page).toHaveURL(`${origin}/g/${seat.code}`);
  await expect(page.getByRole("dialog", { name: "How Cambio works" })).toHaveCount(0);
  await expect(page.getByText("Jordan Lane", { exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByText("Jordan Lane", { exact: true })).toBeVisible();
  const after = await (await context.request.get(`/api/games/${seat.code}/state`)).json();
  expect(after.me).toBe(before.me);
  expect(after.view.public.players.filter((p: { profileId: string | null }) => p.profileId)).toHaveLength(1);
  await host.close();
});

test("signup from a player profile returns to that player before adding them", async ({ page, browser }) => {
  const owner = await browser.newContext({ baseURL: origin });
  const ownerName = username();
  expect((await post(owner, "/api/account", { username: ownerName, displayName: "Riley Chen", password })).status()).toBe(201);
  await page.goto(`/p/${ownerName}`);
  await page.getByRole("link", { name: "Log in to add friends" }).click();
  await page.getByRole("button", { name: "Create account", exact: true }).click();
  const form = page.getByRole("form", { name: "Create account", exact: true });
  await form.getByLabel("Username", { exact: true }).fill(username());
  await form.getByLabel("Display name", { exact: true }).fill("Sam Rivera");
  await form.getByLabel("Password", { exact: true }).fill(password);
  await form.getByLabel("Confirm password", { exact: true }).fill(password);
  await form.getByRole("button", { name: "Create account", exact: true }).click();
  await expect(page).toHaveURL(`${origin}/p/${ownerName}`);
  await expect(page.getByRole("heading", { name: "Riley Chen", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Add friend", exact: true }).click();
  await expect(page.getByRole("button", { name: "Request sent" })).toBeDisabled();
  await page.reload();
  await expect(page.getByRole("button", { name: "Request sent" })).toBeDisabled();
  await page.getByRole("link", { name: "Account settings" }).click();
  await expect(page.getByRole("link", { name: "Back to the profile" })).toHaveAttribute("href", `/p/${ownerName}`);
  await page.goto("/login?next=//example.com");
  await expect(page).toHaveURL(`${origin}/`);
  await owner.close();
});

test("table setup asks once and carries the chosen table through signup", async ({ page, context, browser }) => {
  const host = await browser.newContext({ baseURL: origin });
  const seat = await (await post(host, "/api/games", { name: "Guest Host" })).json();
  await page.goto("/");
  await expect(page.getByRole("form", { name: "Table setup" })).toBeVisible();
  await expect(page.getByLabel("Display name", { exact: true })).toHaveCount(1);
  await expect(page.getByRole("form", { name: "Create account", exact: true })).toHaveCount(0);
  await page.getByLabel("Display name", { exact: true }).fill("Casey Lane");
  await page.getByRole("button", { name: "Join with code" }).click();
  await page.getByLabel("Table code", { exact: true }).fill(seat.code.toLowerCase());
  await page.getByRole("button", { name: "New table", exact: true }).click();
  await expect(page.getByLabel("Display name", { exact: true })).toHaveValue("Casey Lane");
  await page.getByRole("button", { name: "Join with code" }).click();
  await expect(page.getByLabel("Table code", { exact: true })).toHaveValue(seat.code);
  await page.screenshot({ path: "test-results/play-guest.png", fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: "test-results/play-guest-mobile.png", fullPage: true });
  await page.getByRole("link", { name: "Create an account to save your stats" }).click();
  const signup = page.getByRole("form", { name: "Create account", exact: true });
  await expect(signup.getByLabel("Display name", { exact: true })).toHaveValue("Casey Lane");
  await signup.getByLabel("Username", { exact: true }).fill(username());
  await signup.getByLabel("Password", { exact: true }).fill(password);
  await signup.getByLabel("Confirm password", { exact: true }).fill(password);
  await signup.getByRole("button", { name: "Create account", exact: true }).click();
  await expect(page).toHaveURL(`${origin}/g/${seat.code}`);
  await expect(page.getByRole("form", { name: "Join table" })).toContainText("Playing as Casey Lane");
  await page.goto("/");
  await expect(page.getByText("Casey Lane", { exact: true })).toHaveCount(1);
  await expect(page.getByRole("region", { name: "Friends", exact: true })).toHaveCount(1);
  await expect(page.getByRole("region", { name: "Casey Lane's record" })).toHaveCount(0);
  await page.screenshot({ path: "test-results/play-account-mobile.png", fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.screenshot({ path: "test-results/play-account.png", fullPage: true });
  const account = await (await context.request.get("/api/account")).json();
  await page.getByRole("link", { name: "Your record", exact: true }).click();
  await expect(page).toHaveURL(`${origin}/p/${account.username}`);
  await expect(page.getByRole("region", { name: "Casey Lane's record" })).toHaveCount(1);
  await page.getByRole("link", { name: "Account settings" }).click();
  await page.getByRole("button", { name: "Change username" }).click();
  const rename = page.getByRole("form", { name: "Username settings" });
  const nextUsername = username();
  await rename.getByLabel("Username", { exact: true }).fill(nextUsername);
  await rename.getByLabel("Current password", { exact: true }).fill(password);
  await rename.getByRole("button", { name: "Save username" }).click();
  await expect(page.getByRole("status")).toContainText("Username updated");
  await expect(page.getByRole("link", { name: "Back to the profile" })).toHaveAttribute("href", `/p/${nextUsername}`);
  await page.getByRole("link", { name: "Back to the profile" }).click();
  await expect(page).toHaveURL(`${origin}/p/${nextUsername}`);
  await expect(page.getByRole("heading", { name: "Casey Lane", exact: true })).toBeVisible();
  await host.close();
});

test("guest play stays available and the walkthrough is only automatic once", async ({ page, context }) => {
  await page.goto("/");
  await page.getByLabel("Display name", { exact: true }).fill("Guest Player");
  await page.getByRole("button", { name: "Open a table", exact: true }).click();
  await expect(page.getByRole("dialog", { name: "How Cambio works" })).toBeVisible();
  await page.getByRole("button", { name: "Skip", exact: true }).click();
  await expect(page.getByRole("button", { name: "Start round", exact: true })).toBeVisible();
  await expect(page.getByRole("link", { name: /Log in|Create account/ })).toHaveCount(0);
  await page.reload();
  await expect(page.getByRole("button", { name: "Start round", exact: true })).toBeVisible();
  await expect(page.getByRole("dialog", { name: "How Cambio works" })).toHaveCount(0);
  expect((await (await context.request.get("/api/account")).json()).profile).toBeNull();
  await page.getByRole("button", { name: "Leave", exact: true }).click();
  await page.getByRole("button", { name: "Leave", exact: true }).click();
  await expect(page).toHaveURL(`${origin}/`);
  await expect(page.getByLabel("Display name", { exact: true })).toHaveValue("Guest Player");
  await page.getByRole("button", { name: "How to play", exact: true }).click();
  const walkthrough = page.getByRole("dialog", { name: "How Cambio works" });
  const rules = page.getByRole("dialog", { name: "How to play", exact: true });
  await expect(rules).toBeVisible();
  await expect(walkthrough).toHaveCount(0);
  await rules.getByRole("button", { name: "Show walkthrough again" }).click();
  await expect(walkthrough).toContainText("1 of 4");
  await walkthrough.getByRole("button", { name: "Next", exact: true }).click();
  await expect(walkthrough).toContainText("2 of 4");
  await walkthrough.getByRole("button", { name: "Read full rules" }).click();
  await expect(walkthrough).toHaveCount(0);
  await rules.getByRole("button", { name: "Show walkthrough again" }).click();
  await expect(walkthrough).toContainText("1 of 4");
  await walkthrough.getByRole("button", { name: "Skip", exact: true }).click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
});

test("How to play shows the walkthrough once, then remembers the text rules", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("button", { name: "How to play", exact: true }).click();
  const walkthrough = page.getByRole("dialog", { name: "How Cambio works" });
  const rules = page.getByRole("dialog", { name: "How to play", exact: true });
  await expect(walkthrough).toContainText("1 of 4");
  await expect(rules).toHaveCount(0);
  for (let step = 2; step <= 4; step++) {
    await walkthrough.getByRole("button", { name: "Next", exact: true }).click();
    await expect(walkthrough).toContainText(`${step} of 4`);
  }
  await walkthrough.getByRole("button", { name: "Got it", exact: true }).click();
  await page.getByRole("button", { name: "How to play", exact: true }).click();
  await expect(walkthrough).toHaveCount(0);
  await expect(rules).toBeVisible();
  for (const heading of ["Goal", "Your turn", "Powers", "Sticking", "Cambio", "Scores"]) {
    await expect(rules.getByRole("heading", { name: heading, exact: true })).toBeVisible();
  }
  await rules.getByRole("button", { name: "Show walkthrough again" }).click();
  await expect(rules).toHaveCount(0);
  await expect(walkthrough).toContainText("1 of 4");
  await walkthrough.getByRole("button", { name: "Skip", exact: true }).click();
  await page.reload();
  await page.getByRole("button", { name: "How to play", exact: true }).click();
  await expect(rules).toBeVisible();
  await expect(walkthrough).toHaveCount(0);
});
