-- A credential account has one username for both login and public lookup.
-- Keep the historical handle field for existing profile and social RPCs.
begin;
lock table private.accounts, public.profiles in share row exclusive mode;

-- Preserve every login and profile ID. Move only autogenerated legacy names
-- that conflict with an account username. Park changed account names too, so
-- even accounts whose old public names are swapped can be migrated safely.
do $$
declare v_id uuid; v_name text;
begin
  for v_id in
    select p.id from public.profiles p
    where exists (select 1 from private.accounts a where a.profile_id = p.id and a.username <> p.handle)
      or exists (select 1 from private.accounts a where a.username = p.handle and a.profile_id <> p.id)
  loop
    loop
      v_name := 'player' || substr(replace(gen_random_uuid()::text, '-', ''), 1, 12);
      exit when not exists (select 1 from public.profiles where handle = v_name)
        and not exists (select 1 from private.accounts where username = v_name);
    end loop;
    update public.profiles set handle = v_name where id = v_id;
  end loop;
  update public.profiles p set handle = a.username
    from private.accounts a where p.id = a.profile_id and p.handle <> a.username;
end $$;

-- Credentials are the authority for the username. Registration and renaming
-- change public lookup in the same transaction; uniqueness rejects conflicts.
create function private.sync_account_username() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  update public.profiles set handle = new.username where id = new.profile_id;
  return new;
end $$;
revoke all on function private.sync_account_username() from public, anon, authenticated;
create trigger account_username_sync after insert or update of username on private.accounts
  for each row execute function private.sync_account_username();

create or replace function public.account_register(
  p_secret text, p_username text, p_display_name text, p_handle text,
  p_password_hash text, p_session_hash text, p_legacy_hash text default null
) returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_id uuid;
begin
  perform private.check_secret(p_secret);
  if p_legacy_hash is not null then
    select id into v_id from public.profiles where token_hash = p_legacy_hash for update;
    if v_id is null or exists (select 1 from private.accounts where profile_id = v_id) then
      raise exception 'legacy_expired';
    end if;
    update public.profiles set display_name = p_display_name where id = v_id;
  else
    -- p_handle remains in the RPC signature for deployed clients, but no
    -- separate public name is generated or silently suffixed anymore.
    insert into public.profiles(handle, display_name, token_hash)
      values (p_username, p_display_name, p_session_hash) returning id into v_id;
    insert into public.presence(profile_id) values (v_id);
  end if;
  insert into private.accounts(profile_id, username, password_hash) values (v_id, p_username, p_password_hash);
  insert into private.account_sessions(token_hash, profile_id) values (p_session_hash, v_id);
  return jsonb_build_object('profile', private.profile_row(v_id), 'username', p_username);
end $$;

notify pgrst, 'reload schema';
commit;
